package ku_rum.backend.global.config.dataInsert;

import ku_rum.backend.domain.building.domain.Building;
import ku_rum.backend.domain.building.domain.BuildingAbbrev;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.ArrayList;

@Component
public class BuildingInitializer {
  public static ArrayList<Building> initialize() {
    ArrayList<Building> buildings = new ArrayList<>();

    buildings.add(
            Building.of(
                    BuildingAbbrev.경영.name(),
                    2L,
                    BuildingAbbrev.경영.getOriginalName(),
                    BigDecimal.valueOf(37.544419),
                    BigDecimal.valueOf(127.076370))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.상허관.name(),
                    3L,
                    BuildingAbbrev.상허관.getOriginalName(),
                    BigDecimal.valueOf(37.544292),
                    BigDecimal.valueOf(127.076212))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.사.name(),
                    4L,
                    BuildingAbbrev.사.getOriginalName(),
                    BigDecimal.valueOf(37.544073),
                    BigDecimal.valueOf(127.073994))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.예.name(),
                    5L,
                    BuildingAbbrev.예.getOriginalName(),
                    BigDecimal.valueOf(37.544419),
                    BigDecimal.valueOf(127.073994))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.언어원.name(),
                    6L,
                    BuildingAbbrev.언어원.getOriginalName(),
                    BigDecimal.valueOf(37.542497),
                    BigDecimal.valueOf(127.074584))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.종강.name(),
                    8L,
                    BuildingAbbrev.종강.getOriginalName(),
                    BigDecimal.valueOf(37.542260),
                    BigDecimal.valueOf(127.073637))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.의.name(),
                    10L,
                    BuildingAbbrev.의.getOriginalName(),
                    BigDecimal.valueOf(37.541443),
                    BigDecimal.valueOf(127.072313))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.생.name(),
                    11L,
                    BuildingAbbrev.생.getOriginalName(),
                    BigDecimal.valueOf(37.541004),
                    BigDecimal.valueOf(127.074197))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.동.name(),
                    12L,
                    BuildingAbbrev.동.getOriginalName(),
                    BigDecimal.valueOf(37.540242),
                    BigDecimal.valueOf(127.074289))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.산학.name(),
                    14L,
                    BuildingAbbrev.산학.getOriginalName(),
                    BigDecimal.valueOf(37.539701),
                    BigDecimal.valueOf(127.073102))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.수.name(),
                    15L,
                    BuildingAbbrev.수.getOriginalName(),
                    BigDecimal.valueOf(37.539294),
                    BigDecimal.valueOf(127.074676))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.새.name(),
                    16L,
                    BuildingAbbrev.새.getOriginalName(),
                    BigDecimal.valueOf(37.543549),
                    BigDecimal.valueOf(127.077408))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.건.name(),
                    17L,
                    BuildingAbbrev.건.getOriginalName(),
                    BigDecimal.valueOf(37.543391),
                    BigDecimal.valueOf(127.078521))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.부.name(),
                    18L,
                    BuildingAbbrev.부.getOriginalName(),
                    BigDecimal.valueOf(37.543443),
                    BigDecimal.valueOf(127.078225))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.문.name(),
                    19L,
                    BuildingAbbrev.문.getOriginalName(),
                    BigDecimal.valueOf(37.542422),
                    BigDecimal.valueOf(127.078929))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.공.name(),
                    21L,
                    BuildingAbbrev.공.getOriginalName(),
                    BigDecimal.valueOf(37.541822),
                    BigDecimal.valueOf(127.078845))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.신공.name(),
                    22L,
                    BuildingAbbrev.신공.getOriginalName(),
                    BigDecimal.valueOf(37.540579),
                    BigDecimal.valueOf(127.079472))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.이.name(),
                    23L,
                    BuildingAbbrev.이.getOriginalName(),
                    BigDecimal.valueOf(37.541646),
                    BigDecimal.valueOf(127.080408))
    );
    buildings.add(
            Building.of(
                    BuildingAbbrev.창.name(),
                    24L,
                    BuildingAbbrev.창.getOriginalName(),
                    BigDecimal.valueOf(37.540757),
                    BigDecimal.valueOf(127.079368))
    );
    return buildings;
  }
}